### PR TITLE
Patch 6

### PR DESCRIPTION
**Pull request by dedalgr**
How much will it cost me to make me a template for a women's store.
Of course I can modify the template, but I don't care. With only one payment upon delivery and sending an email (I did the email at 80%) 

I confuse with git again.

### CODE REVIEW

**Comment by dedalgr** [comment]
I confuse with git again. 

How much will it cost me to make me a template for a women's store.
Of course I can modify the template, but I don't care. With only one payment upon delivery and sending an email (I did the email at 80%)

**Comment by dedalgr** [comment]
I confuse with git again.

How much will it cost me to make me a template for a women's store.
Of course I can modify the template, but I don't care. With only one payment upon delivery and sending an email (I did the email at 80%)

**Review by hjlarry — COMMENTED** [review]
LGTM

**Comment by hjlarry** [comment]
> How much will it cost me to make me a template for a women's store. Of course I can modify the template, but I don't care. With only one payment upon delivery and sending an email (I did the email at 80%)
> 
> I confuse with git again.

thanks for multi-lang support, and I don`t understand what this mean.

**Pull request merged**
